# Generated by Django 4.2 on 2023-04-18 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="year_of_experience",
        ),
    ]
