# Generated by Django 4.2 on 2023-04-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_remove_cook_year_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
