# Generated by Django 4.2 on 2023-04-25 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_cook_years_of_experience"),
    ]

    operations = []
