# Generated by Django 4.2 on 2023-04-28 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0004_auto_20230425_1511"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ["username"]},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "dishes"},
        ),
    ]
